graduate_student/graduate_student/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('students/', include('students.urls',)),
    path('company/', include('company.urls')),
    path('create/', include('create.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

graduate_student/main/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.index, name='home'),
    path('about', views.about, name='about'),
    path('login/', auth_views.LoginView.as_view(template_name='main/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='home'), name='logout')
]

graduate_student/students/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.student_storage, name='students'),
    path('<int:pk>', views.PersonDetailView.as_view(), name='person-detail'),
    path('<int:pk>/personal/', views.personal_details, name='personal_details'),
    path('<int:pk>/personal/pdf/', views.export_to_pdf, name='export_personal_pdf'),
    path('<int:pk>/employment/', views.employment_details, name='employment_details')
]

graduate_student/students/models.py
from django.db import models
from company.models import Company

# Модель для информации о выпускнике
class Graduate(models.Model):
    full_name = models.CharField('ФИО',max_length=100)
    date_of_birth = models.DateField('Дата Рождения')
    GENDER_CHOICES = [
        ('M', 'Мужской'),
        ('F', 'Женский'),
    ]
    gender = models.CharField('Пол',max_length=1, choices=GENDER_CHOICES)
    citizenship = models.CharField('Гражданство', max_length=100)
    address = models.CharField('Адрес проживания', max_length=200)
    phone_number = models.CharField('Телефон', max_length=15)
    email = models.EmailField('Электронная почта')
    snils = models.CharField('СНИЛС', max_length=20)
    study_direction_code = models.CharField('Код направления подготовки', max_length=20)
    study_direction_name = models.CharField('Название направления подготовки', max_length=200)
    study_direction_profile = models.CharField('Профиль направления подготовки', max_length=200)
    enrollment_year = models.IntegerField('Год поступления')
    graduation_year = models.IntegerField('Год окончания')
    EDUCATION_FORM_CHOICES = [
        ('Full-time', 'Очная'),
        ('Part-time', 'Заочная'),
    ]
    education_form = models.CharField('Форма обучения',max_length=20, choices=EDUCATION_FORM_CHOICES)
    employment_book = models.BooleanField('Наличие трудовой книжки')

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = 'Выпускника'
        verbose_name_plural = 'Выпускники'

# Модель для информации о трудовой деятельности выпускника
class EmploymentHistory(models.Model):
    graduate = models.ForeignKey(Graduate, on_delete=models.CASCADE, verbose_name='Выпускник')
    employment_placework = models.ForeignKey(Company,  on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Место работы')
    employment_status = models.CharField('Должность', max_length=40, default='Безработный')
    change_date = models.DateField('Дата')

    def __str__(self):
        return f"{self.graduate.full_name} - {self.change_date}"

    class Meta:
        verbose_name = 'Трудовая выпускника'
        verbose_name_plural = 'Трудовые выпускников'

graduate_student/students/forms.py
from django import forms
from .models import Graduate, EmploymentHistory

class GraduateForm(forms.ModelForm):
    class Meta:
        model = Graduate
        fields = [
            'full_name',
            'date_of_birth',
            'gender',
            'citizenship',
            'address',
            'phone_number',
            'email',
            'snils',
            'study_direction_code',
            'study_direction_name',
            'study_direction_profile',
            'enrollment_year',
            'graduation_year',
            'education_form',
            'employment_book'
        ]
        widgets = {
            'date_of_birth': forms.DateInput(attrs={'type': 'date'}),
        }


class HistoryForm(forms.ModelForm):
    class Meta:
        model = EmploymentHistory
        fields = [
            'graduate',
            'employment_placework',
            'employment_status',
            'change_date'
        ]

graduate_student/students/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.views.generic import DetailView
from django.http import HttpResponse
from .models import Graduate, EmploymentHistory
from io import BytesIO
from reportlab.pdfgen import canvas
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase import pdfmetrics
from reportlab.lib.pagesizes import A4
from reportlab.lib.utils import ImageReader
import textwrap
from django.contrib.auth.decorators import login_required

@login_required
def student_storage(request):
    query = request.GET.get('q')
    if query:
        all_objects = Graduate.objects.filter(full_name__icontains=query).order_by('full_name')
    else:
        all_objects = Graduate.objects.all().order_by('full_name')

    paginator = Paginator(all_objects, 10)  # Разбиваем на страницы, по 10 объектов на каждой странице
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'students/persons.html', {'page_obj': page_obj})


class PersonDetailView(DetailView):
    model = Graduate
    template_name = 'students/details_view.html'
    context_object_name = 'graduate'

@login_required
def personal_details(request, pk):
    graduate = get_object_or_404(Graduate, pk=pk)
    return render(request, 'students/personal_details.html', {'graduate': graduate})

@login_required
def employment_details(request, pk):
    graduate = get_object_or_404(Graduate, pk=pk)
    employment_history = EmploymentHistory.objects.filter(graduate=graduate)
    return render(request, 'students/employment_details.html', {'graduate': graduate, 'employment_history': employment_history})


@login_required
def export_to_pdf(request, pk):
    graduate = get_object_or_404(Graduate, pk=pk)
    employment_history = EmploymentHistory.objects.filter(graduate=graduate).order_by('change_date')

    # Создание PDF-файла
    buffer = BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=A4)

    # Регистрация шрифта, поддерживающего кириллицу
    pdfmetrics.registerFont(TTFont('Arial-Bold', 'Arial-Bold.ttf'))
    pdfmetrics.registerFont(TTFont('Arial', 'Arial.ttf'))

    # Загрузка изображения для фона
    background_image = ImageReader('pdf_background.jpg')

    # Получение размеров страницы
    width, height = A4

    # Рисование фона
    pdf.drawImage(background_image, 0, 0, width=width, height=height)

    # Установка начальной позиции по вертикали
    y_position = 800  # Начальная позиция по вертикали, учитывая размер страницы A4

    # Заполнение PDF-файла данными о студенте
    data = [
        ('ФИО', graduate.full_name),
        ('Дата рождения', graduate.date_of_birth),
        ('Пол', graduate.gender),
        ('Гражданство', graduate.citizenship),
        ('Адрес проживания', graduate.address),
        ('Телефон', graduate.phone_number),
        ('Электронная почта', graduate.email),
        ('СНИЛС', graduate.snils),
        ('Код направления подготовки', graduate.study_direction_code),
        ('Название направления подготовки', graduate.study_direction_name),
        ('Профиль направления подготовки', graduate.study_direction_profile),
        ('Год поступления', graduate.enrollment_year),
        ('Год окончания', graduate.graduation_year),
        ('Форма обучения', graduate.education_form)
    ]

    max_width = 500  # Максимальная ширина строки

    for label, value in data:
        # Рисуем заголовок жирным шрифтом
        pdf.setFont("Arial-Bold", 12)
        label_text = f'{label}: '
        pdf.drawString(50, y_position, label_text)

        # Определяем позицию для значения
        text_width = pdf.stringWidth(label_text, "Arial-Bold", 12)

        # Разбиваем значение на строки
        wrapped_text = textwrap.wrap(str(value), width=(max_width - text_width) // 8)

        pdf.setFont("Arial", 12)
        for line in wrapped_text:
            pdf.drawString(50 + text_width, y_position, line)
            y_position -= 10  # уменьшаем позицию по вертикали для следующей строки

        y_position -= 20  # дополнительный отступ между записями

    y_position -= 40
    # Заполнение PDF-файла трудовой историей выпускника
    pdf.setFont("Arial-Bold", 14)
    pdf.drawString(50, y_position, "Трудовая история:")
    y_position -= 30  # отступ перед трудовой историей

    pdf.setFont("Arial", 12)
    for record in employment_history:
        company_name = record.employment_placework.name if record.employment_placework else "Поставлен на учёт"
        employment_line = f'{record.change_date} - {company_name} - {record.employment_status}'

        # Разбиваем строку на несколько, если она слишком длинная
        wrapped_text = textwrap.wrap(employment_line, width=max_width // 8)

        for line in wrapped_text:
            pdf.drawString(50, y_position, line)
            y_position -= 10  # уменьшаем позицию по вертикали для следующей строки

        y_position -= 20  # дополнительный отступ между записями трудовой истории

    pdf.showPage()
    pdf.save()

    buffer.seek(0)

    # Отправка PDF в HTTP response
    response = HttpResponse(buffer, content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename="{graduate.full_name}_details.pdf"'

    return response

graduate_student/students/templates/students/details_view.html
{% extends 'main/global_pattern.html' %}
{% load static %}

{% block title %} {{ graduate.full_name }} {% endblock %}

{% block content %}
    <div class="features">
        <div class="header">
            <h1>{{ graduate.full_name }}</h1>
            <form action="{% url 'export_personal_pdf' pk=graduate.pk %}" method="get" class="pdf-form">
                <button type="submit" class="pdf-button">Скачать PDF</button>
            </form>
        </div>
        <a href="{% url 'personal_details' pk=graduate.pk %}"><li><i>Личные данные</i></li></a>
        <a href="{% url 'employment_details' pk=graduate.pk %}"><li><i>Данные по трудоустройству</i></li></a>
    </div>
{% endblock %}

graduate_student/students/templates/students/employment_details.html
{% extends 'main/global_pattern.html' %}
{% load static %}

{% block title %} {{ graduate.full_name }} {% endblock %}

{% block content %}
<div class="data_list">
    <h1>{{ graduate.full_name }}</h1>
    {% for employment in employment_history|dictsort:"change_date" reversed %}
        <div>
            <p>{% if employment.change_date %}<strong>{{ employment.change_date }} - {% endif %}{{ employment.employment_placework|default:"Поставлен на учёт" }} - {{ employment.employment_status }}</strong></p>
        </div>
    {% empty %}
        <p>Нет данных о трудовой истории</p>
    {% endfor %}
    <p><strong>Наличие трудовой книжки: </strong>{{ graduate.employment_book|yesno:"Имеется,Не имеется" }}</p>
</div>
{% endblock %}

graduate_student/students/templates/students/personal_details.html
{% extends 'main/global_pattern.html' %}
{% load static %}

{% block title %} {{ graduate.full_name }} {% endblock %}

{% block content %}
    <div class="data_list">
    <h1>Информация о выпускнике</h1>
    <p><strong>ФИО:</strong> {{ graduate.full_name }}</p>
    <p><strong>Дата рождения:</strong> {{ graduate.date_of_birth }}</p>
    <p><strong>Пол:</strong> {{ graduate.get_gender_display }}</p>
    <p><strong>Гражданство:</strong> {{ graduate.citizenship }}</p>
    <p><strong>Адрес проживания:</strong> {{ graduate.address }}</p>
    <p><strong>Телефон:</strong> {{ graduate.phone_number }}</p>
    <p><strong>Электронная почта:</strong> {{ graduate.email }}</p>
    <p><strong>СНИЛС:</strong> {{ graduate.snils }}</p>
    <p><strong>Код направления подготовки:</strong> {{ graduate.study_direction_code }}</p>
    <p><strong>Название направления подготовки:</strong> {{ graduate.study_direction_name }}</p>
    <p><strong>Профиль направления подготовки:</strong> {{ graduate.study_direction_profile }}</p>
    <p><strong>Год поступления:</strong> {{ graduate.enrollment_year }}</p>
    <p><strong>Год окончания:</strong> {{ graduate.graduation_year }}</p>
    <p><strong>Форма обучения:</strong> {{ graduate.get_education_form_display }}</p>
    </div>
{% endblock %}

graduate_student/students/templates/students/persons.html
{% extends 'main/global_pattern.html' %}
{% load static %}

{% block title %} Выпускники {% endblock %}

{% block content %}

    <h1>Список выпускников</h1>

    <div class="search-box">
        <form method="get">
            <input type="text" name="q" placeholder="Введите запрос..." value="{{ request.GET.q }}">
            <input type="submit" value="Поиск">
        </form>
    </div>

    <div class="persons">
        {% if page_obj %}
            {% for el in page_obj %}
                <div>
                    <a href="{% url 'person-detail' el.id %}">{{ el.full_name }}</a>
                </div>
            {% endfor %}
        {% else %}
            <p>У вас нет записей!</p>
        {% endif %}
    </div>

    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">&laquo; первая</a>
                <a href="?page={{ page_obj.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">предыдущая</a>
            {% endif %}

            <span class="current">
                Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">следующая</a>
                <a href="?page={{ page_obj.paginator.num_pages }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">последняя &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endblock %}